MasterBlogger.Presentation.MVCCore/Areas/Administrator/Pages/ArticleCategoryManagement/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleCategoryManagement
{
    public class CreateModel : PageModel
    {
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
        }

        public RedirectToPageResult OnPost(CreateArticleCategory command)
        {
            _articleCategoryApplication.Create(command);
            return RedirectToPage("./List");
        }
    }
}

MasterBlogger.Presentation.MVCCore/Areas/Administrator/Pages/ArticleCategoryManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleCategoryManagement
{
    public class EditModel : PageModel
    {
        [BindProperty] public RenameArticleCategory ArticleCategory { get; set; }
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(long id)
        {
            ArticleCategory = _articleCategoryApplication.Get(id);
        }

        public RedirectToPageResult OnPost()
        {
            _articleCategoryApplication.Rename(ArticleCategory);
            return RedirectToPage("./List");
        }
    }
}

MasterBlogger.Presentation.MVCCore/Areas/Administrator/Pages/ArticleCategoryManagement/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleCategoryManagement
{
    public class ListModel : PageModel
    {
        public List<ArticleCategoryViewModel> ArticleCategories { get; set; }
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public ListModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
            this.ArticleCategories = _articleCategoryApplication.List();
        }

        public RedirectToPageResult OnPostRemove(long id)
        {
            _articleCategoryApplication.Remove(id);
            return RedirectToPage("./List");
        }

        public RedirectToPageResult OnPostActivate(long id)
        {
            _articleCategoryApplication.Activate(id);
            return RedirectToPage("./List");
        }
    }
}

MasterBlogger.Presentation.MVCCore/Areas/Administrator/Pages/ArticleManagement/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application.Contracts.Article;
using MB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleManagement
{
    public class CreateModel : PageModel
    {
        public List<SelectListItem> ArticleCategories { get; set; }

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleCategoryApplication articleCategoryApplication, IArticleApplication articleApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            ArticleCategories = _articleCategoryApplication.List()
                .Select(x => new SelectListItem(x.Title, x.Id.ToString())).ToList();
        }

        public RedirectToPageResult OnPost(CreateArticle command)
        {
            _articleApplication.Create(command);
            return RedirectToPage("./List");
        }
    }
}

MasterBlogger.Presentation.MVCCore/Areas/Administrator/Pages/ArticleManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application.Contracts.Article;
using MB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleManagement
{
    public class EditModel : PageModel
    {
        [BindProperty] public EditArticle Article { get; set; }

        public List<SelectListItem> ArticleCategories { get; set; }

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(long id)
        {
            Article = _articleApplication.Get(id);
            ArticleCategories = _articleCategoryApplication.List()
                .Select(x => new SelectListItem(x.Title, x.Id.ToString())).ToList();
        }

        public RedirectToPageResult OnPost()
        {
            _articleApplication.Edit(Article);
            return  RedirectToPage("./List");
        }
    }
}

MasterBlogger.Presentation.MVCCore/Areas/Administrator/Pages/ArticleManagement/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application.Contracts.Article;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleManagement
{
    public class ListModel : PageModel
    {
        public List<ArticleViewModel> Articles { get; set; }
        private readonly IArticleApplication _articleApplication;

        public ListModel(IArticleApplication articleApplication)
        {
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            Articles = _articleApplication.GetList();
        }

        public RedirectToPageResult OnPostRemove(long id)
        {
            _articleApplication.Remove(id);
            return RedirectToPage("./List");
        }

        public RedirectToPageResult OnPostActivate(long id)
        {
            _articleApplication.Activate(id);
            return RedirectToPage("./List");
        }
    }
}

MasterBlogger.Presentation.MVCCore/Areas/Administrator/Pages/CommentManagement/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application.Contracts.Comment;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore.Areas.Administrator.Pages.CommentManagement
{
    public class ListModel : PageModel
    {
        public List<CommentViewModel> Comments { get; set; }    
        private readonly ICommentApplication _commentApplication;

        public ListModel(ICommentApplication commentApplication)
        {
            _commentApplication = commentApplication;
        }

        public void OnGet()
        {
            this.Comments = _commentApplication.GetList();
        }

        public RedirectToPageResult OnPostConfirm(long id)
        {
            _commentApplication.Confirm(id);
            return RedirectToPage("./List");
        } 
        public RedirectToPageResult OnPostCancel(long id)
        {
            _commentApplication.Cancel(id);
            return RedirectToPage("./List");
        }
    }
}

MasterBlogger.Presentation.MVCCore/Areas/Administrator/Pages/ArticleManagement/Create.cshtml
@page
@model MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleManagement.CreateModel
@{
}

<div class="card">
    <div class="card-header">
        <h2>Create New Article</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="Title" class="control-label">Title:</label>
                            <input name="Title" id="Title" class="form-control" />
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="ShortDescription" class="control-label">Short Description:</label>
                            <textarea name="ShortDescription" id="ShortDescription" class="form-control" rows="3"></textarea>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="Image" class="control-label">Image:</label>
                            <input name="Image" id="Image" class="form-control"/>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="Content" class="control-label">Content:</label>
                            <textarea name="Content" id="Content" class="form-control" rows="5"></textarea>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="Content" class="control-label">Article Category:</label>
                            <select asp-items="Model.ArticleCategories" name="ArticleCategoryId" id="ArticleCategoryId" class="form-control">  
                                <option value="0">Select Article Category</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-success" />
                        <a class="btn btn-dark" asp-page="./List" asp-area="Administrator">Back to list</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MasterBlogger.Presentation.MVCCore/Areas/Administrator/Pages/ArticleManagement/Edit.cshtml
@page "{id:long}"
@model MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleManagement.EditModel
@{
}

<div class="card">
    <div class="card-header">
        <h2>Edit Article Category: @Model.Article.Title</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Article.Id" />
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="Article.Title" class="control-label">Title:</label>
                            <input asp-for="Article.Title" class="form-control" />
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="Article.ShortDescription" class="control-label">Short Description:</label>
                            <textarea asp-for="Article.ShortDescription" class="form-control" rows="3"></textarea>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="Article.Content" class="control-label">Content:</label>
                            <textarea asp-for="Article.Content" class="form-control" rows="5"></textarea>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="Article.Image" class="control-label">Image:</label>
                            <input asp-for="Article.Image" class="form-control" />
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="Article.ArticleCategoryId" class="control-label">Article Category:</label>
                            <select asp-for="Article.ArticleCategoryId" asp-items="Model.ArticleCategories" class="form-control" rows="5">
                                <option value="0">Select Article Category</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Edit" class="btn btn-warning" />
                        <a class="btn btn-dark" asp-page="./List" asp-area="Administrator">Back to list</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MasterBlogger.Presentation.MVCCore/Areas/Administrator/Pages/ArticleManagement/List.cshtml
@page
@model MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleManagement.ListModel
@{
}

<div class="card">
    <div class="card-header">
        <h3 class="float-left">Article List</h3>
        <div class="float-right">
            <a class="btn btn-success" asp-page="./Create" asp-area="Administrator">Add New</a>
        </div>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Article Category</th>
                    <th>Statuses</th>
                    <th>Creation Date</th>
                    <th>Operations</th>
                </tr>
            </thead>
            <thead>
                @foreach (var article in Model.Articles)
                {
                    <tr>
                        <td>@article.Id</td>
                        <td>@article.Title</td>
                        <td>@article.ArticleCategory</td>
                        <td>
                            @if (article.IsDeleted)
                            {
                                <i class="fa fa-close fa-2x text-danger"></i>
                            }
                            else
                            {
                                <i class="fa fa-check fa-2x text-success"></i>

                            }
                        </td>
                        <td>@article.CreationDate</td>
                        <td>
                            <a class="btn btn-warning float-left mr-3" asp-page="./Edit" asp-route-id="@article.Id">Edit</a>
                            @if (article.IsDeleted)
                            {
                                <form method="post" asp-page-handler="Activate" class="float-left ">
                                    <button class="btn btn-success">Activate</button>
                                    <input type="hidden" name="id" value="@article.Id" />
                                </form>
                            }
                            else
                            {
                                <form method="post" asp-page-handler="Remove" class="float-left ">
                                    <button class="btn btn-danger">Remove</button>
                                    <input type="hidden" name="id" value="@article.Id" />
                                </form>
                            }
                        </td>
                    </tr>
                }
            </thead>
        </table>
    </div>
</div>