MasterBlogger.Presentation.MVCCore/Areas/Administrator/Pages/ArticleCategoryManagement/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleCategoryManagement
{
    public class ListModel : PageModel
    {
        public List<ArticleCategoryViewModel> ArticleCategories { get; set; }
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public ListModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
            this.ArticleCategories = _articleCategoryApplication.List();
        }

        public RedirectToPageResult OnPostRemove(long id)
        {
            _articleCategoryApplication.Remove(id);
            return RedirectToPage("./List");
        }

        public RedirectToPageResult OnPostActivate(long id)
        {
            _articleCategoryApplication.Activate(id);
            return RedirectToPage("./List");
        }
    }
}

MasterBlogger.Presentation.MVCCore/Areas/Administrator/Pages/ArticleManagement/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application.Contracts.Article;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleManagement
{
    public class ListModel : PageModel
    {
        public List<ArticleViewModel> Articles { get; set; }
        private readonly IArticleApplication _articleApplication;

        public ListModel(IArticleApplication articleApplication)
        {
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            Articles = _articleApplication.GetList();
        }

        public RedirectToPageResult OnPostRemove(long id)
        {
            _articleApplication.Remove(id);
            return RedirectToPage("./List");
        }

        public RedirectToPageResult OnPostActivate(long id)
        {
            _articleApplication.Activate(id);
            return RedirectToPage("./List");
        }
    }
}

MasterBlogger.Presentation.MVCCore/Areas/Administrator/Pages/CommentManagement/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application.Contracts.Comment;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore.Areas.Administrator.Pages.CommentManagement
{
    public class ListModel : PageModel
    {
        public List<CommentViewModel> Comments { get; set; }    
        private readonly ICommentApplication _commentApplication;

        public ListModel(ICommentApplication commentApplication)
        {
            _commentApplication = commentApplication;
        }

        public void OnGet()
        {
            this.Comments = _commentApplication.GetList();
        }

        public RedirectToPageResult OnPostConfirm(long id)
        {
            _commentApplication.Confirm(id);
            return RedirectToPage("./List");
        } 
        public RedirectToPageResult OnPostCancel(long id)
        {
            _commentApplication.Cancel(id);
            return RedirectToPage("./List");
        }
    }
}

MasterBlogger.Presentation.MVCCore/Areas/Administrator/Pages/CommentManagement/List.cshtml
@page
@using MB.Domain.CommentAgg
@model MB.Presentation.MVCCore.Areas.Administrator.Pages.CommentManagement.ListModel
@{
}

<div class="card">
    <div class="card-header">
        <h3 class="float-left">Comments List</h3>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Message</th>
                    <th>Article</th>
                    <th>Status</th>
                    <th>CreationDate</th>
                    <th>Operation</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var comment in Model.Comments)
                {
                    <tr>
                        <td>@comment.Id</td>
                        <td>@comment.Name</td>
                        <td>@comment.Email</td>
                        <td>@comment.Message</td>
                        <td>@comment.Article</td>
                        <td>
                            @if (comment.Status is Statuses.New)
                            {
                                <i class="fa fa-eye fa-2x text-info"></i>
                            }
                            else if (comment.Status is Statuses.Cancelled)
                            {
                                <i class="fa fa-close fa-2x text-danger"></i>
                            }
                            else
                            {
                                <i class="fa fa-check fa-2x text-success"></i>

                            }
                        </td>
                        <td>@comment.CreationDate</td>
                        <td>
                            @if (comment.Status is Statuses.New)
                            {
                                <form method="post" asp-page-handler="Confirm" class="float-left ">
                                    <button class="btn btn-success">Confirm</button>
                                    <input type="hidden" name="id" value="@comment.Id" />
                                </form>
                                <form method="post" asp-page-handler="Cancel" class="float-left ">
                                    <button class="btn btn-danger">Cancel</button>
                                    <input type="hidden" name="id" value="@comment.Id" />
                                </form>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>